declare module '@/pages/Login';
declare module '@/pages/Notes';
declare module '@/pages/Editor';
declare module '@/pages/Dashboard';
declare module '@/pages/NewNote';
declare module '@/pages/About';
declare module '@/pages/Portfolio';
declare module '@/pages/TextAlter';
declare module '@/pages/IngredientScanner';